meta_product_name: "Invest with us"
meta_title: "Invest within the Corporate cycle"
meta_description: "Mix public and private investment"
meta_image: "boussard_gavaudan.png" # should exist in `app/assets/images/`
twitter_account: "@fxbaud"   # required for Twitter Cards
