meta_product_name: "Invest into the Capital structure"
meta_title: "Corporate cycle"
meta_description: "listed equity and private debt, direct lending, distressed debt, special situations"
meta_image: "boussard_gavaudan.png" # should exist in `app/assets/images/`
twitter_account: "@fxbaud"   # required for Twitter Cards
